//! A text file of paths, one per line, decoded the way this OS writes one.
//!
//! `ren-cli --list` (the legacy `/l`) reads such a file, and it is almost
//! always generated by something else — which on Windows means one of three
//! encodings, and none of them is the UTF-8 a Rust program assumes:
//!
//! * Windows PowerShell 5.1, the one Windows ships, writes **UTF-16LE** with a
//!   byte-order mark from `Out-File` and `>`.
//! * Its `Set-Content`, and `cmd`'s `>` after `chcp` to a Western code page,
//!   write the **ANSI code page**.
//! * PowerShell 7 and nearly everything else write UTF-8, with or without a
//!   mark.
//!
//! So the bytes decide: a UTF-16 mark means UTF-16, a UTF-8 mark is dropped,
//! and text that is not valid UTF-8 falls back to what this OS calls a legacy
//! encoding — the ANSI code page on Windows, and on Unix the raw bytes, which
//! *are* the file name there. The same shape as D50's rule for a CSV.
//!
//! A file with a **NUL byte** in it is UTF-16 even without a mark (`cmd /U`
//! writes those): no path can contain NUL, so a list that has one is not
//! 8-bit text.

use std::ffi::OsString;

/// Every line of `bytes`, decoded, with its line ending and surrounding
/// whitespace removed. Blank lines are kept, as empty strings; what counts as
/// a comment is the caller's format, not the encoding's.
pub fn lines(bytes: &[u8]) -> Vec<OsString> {
    if let Some(rest) = bytes.strip_prefix(&[0xFF, 0xFE]) {
        return utf16_lines(rest, u16::from_le_bytes);
    }
    if let Some(rest) = bytes.strip_prefix(&[0xFE, 0xFF]) {
        return utf16_lines(rest, u16::from_be_bytes);
    }
    if bytes.contains(&0) {
        // Unmarked UTF-16: ASCII's high byte is zero, so the zeros sit at the
        // odd offsets in little-endian and the even ones in big-endian.
        let zero_at_even = bytes.iter().step_by(2).filter(|b| **b == 0).count();
        let zero_at_odd = bytes.iter().skip(1).step_by(2).filter(|b| **b == 0).count();
        return if zero_at_even > zero_at_odd {
            utf16_lines(bytes, u16::from_be_bytes)
        } else {
            utf16_lines(bytes, u16::from_le_bytes)
        };
    }
    let bytes = bytes.strip_prefix(&[0xEF, 0xBB, 0xBF]).unwrap_or(bytes);
    match std::str::from_utf8(bytes) {
        Ok(text) => text_lines(text),
        Err(_) => legacy_lines(bytes),
    }
}

fn text_lines(text: &str) -> Vec<OsString> {
    text.lines()
        .map(|line| OsString::from(line.trim()))
        .collect()
}

/// A lone surrogate — possible in a Windows name, never in a well-formed
/// file — is replaced rather than refused: the path then does not exist, and
/// the caller names it, which is louder than failing the whole list.
fn utf16_lines(bytes: &[u8], unit: fn([u8; 2]) -> u16) -> Vec<OsString> {
    let units: Vec<u16> = bytes
        .chunks_exact(2)
        .map(|pair| unit([pair[0], pair[1]]))
        .collect();
    text_lines(&String::from_utf16_lossy(&units))
}

/// Not UTF-8, so a Unix file name as it is: split on `\n` and kept as bytes.
#[cfg(unix)]
fn legacy_lines(bytes: &[u8]) -> Vec<OsString> {
    use std::os::unix::ffi::OsStringExt;

    bytes
        .split(|b| *b == b'\n')
        .map(|line| OsString::from_vec(line.trim_ascii().to_vec()))
        .collect()
}

/// Not UTF-8, so the ANSI code page — what `Set-Content` writes.
#[cfg(windows)]
fn legacy_lines(bytes: &[u8]) -> Vec<OsString> {
    use windows_sys::Win32::Globalization::{CP_ACP, MultiByteToWideChar};

    let Ok(len) = i32::try_from(bytes.len()) else {
        return text_lines(&String::from_utf8_lossy(bytes));
    };
    // SAFETY: a null output buffer with a zero length asks for the size only;
    // `bytes` is valid for `len` bytes.
    let wanted =
        unsafe { MultiByteToWideChar(CP_ACP, 0, bytes.as_ptr(), len, std::ptr::null_mut(), 0) };
    let Ok(size) = usize::try_from(wanted) else {
        return text_lines(&String::from_utf8_lossy(bytes));
    };
    let mut wide = vec![0u16; size];
    // SAFETY: `wide` has room for exactly the `wanted` units just reported.
    let written =
        unsafe { MultiByteToWideChar(CP_ACP, 0, bytes.as_ptr(), len, wide.as_mut_ptr(), wanted) };
    wide.truncate(usize::try_from(written).unwrap_or(0));
    text_lines(&String::from_utf16_lossy(&wide))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn strings(lines: Vec<OsString>) -> Vec<String> {
        lines
            .into_iter()
            .map(|line| line.into_string().unwrap())
            .collect()
    }

    #[test]
    fn utf8_with_or_without_a_mark_reads_as_itself() {
        assert_eq!(
            strings(lines(b"/a/x.txt\r\n  /a/y.txt \n")),
            ["/a/x.txt", "/a/y.txt"]
        );
        assert_eq!(
            strings(lines("\u{feff}/a/caf\u{e9}.txt\n".as_bytes())),
            ["/a/caf\u{e9}.txt"],
            "the mark is not part of the first path"
        );
    }

    /// Windows PowerShell's `Out-File` and `>`: UTF-16LE with a mark.
    #[test]
    fn utf16_with_a_mark_is_decoded() {
        let text = "C:\\a\\caf\u{e9}.jpg\r\nC:\\a\\b.jpg\r\n";
        let mut le = vec![0xFF, 0xFE];
        let mut be = vec![0xFE, 0xFF];
        for unit in text.encode_utf16() {
            le.extend_from_slice(&unit.to_le_bytes());
            be.extend_from_slice(&unit.to_be_bytes());
        }
        let want = ["C:\\a\\caf\u{e9}.jpg", "C:\\a\\b.jpg"];
        assert_eq!(strings(lines(&le)), want);
        assert_eq!(strings(lines(&be)), want);
    }

    /// `cmd /U` writes UTF-16LE with no mark; a NUL byte gives it away.
    #[test]
    fn utf16_without_a_mark_is_recognised_by_its_zeros() {
        let bytes: Vec<u8> = "C:\\a\\x.jpg\r\n"
            .encode_utf16()
            .flat_map(u16::to_le_bytes)
            .collect();
        assert_eq!(strings(lines(&bytes)), ["C:\\a\\x.jpg"]);
    }

    /// Not UTF-8 on Unix is a file name as the kernel stores it, byte for
    /// byte — a lossy decode would name a file that does not exist.
    #[test]
    #[cfg(unix)]
    fn text_that_is_not_utf8_keeps_its_bytes_on_unix() {
        use std::os::unix::ffi::OsStrExt;

        let got = lines(b"/a/caf\xe9.txt\n/a/b.txt\n");
        assert_eq!(got[0].as_bytes(), b"/a/caf\xe9.txt");
        assert_eq!(got[1], OsString::from("/a/b.txt"));
    }
}
